"""empty message

Revision ID: a1afbecd509c
Revises: 
Create Date: 2019-10-21 19:50:50.111872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1afbecd509c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('up_time', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
